name: Tag

on:
  push:
    tags:
      "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set tag var
        id: vars
        run: |
          git fetch -a
          echo ::set-output name=current_major::$(git tag --sort "-committerdate" | cut -d$'\n' -f1 | cut -d. -f1)
          echo ::set-output name=previous_major::$(git tag --sort "-committerdate" | cut -d$'\n' -f2 | cut -d. -f1)
      - name: Print vars
        run: |
          echo ${{ steps.vars.outputs.current_major }}
          echo ${{ steps.vars.outputs.previous_major }}
      
      - name: SSH Remote Commands
        if: ${{ steps.vars.outputs.current_major == steps.vars.outputs.previous_major }}
        uses: appleboy/ssh-action@v0.1.4
        env:
          PROCESS_PATH: ${{ secrets.CD_PROCESS_PATH }}
          PROCESS_ID: ${{ secrets.CD_PROCESS_ID }}
        with:
          host: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          key: ${{ secrets.CD_SECRET_KEY }}
          script_stop: true
          envs: PROCESS_PATH, PROCESS_ID
          script: |
            cd $PROCESS_PATH
            echo $PROCESS_PATH
            pip install --user -U pipenv
            git fetch --tags
            git checkout $GITHUB_REF
            python3 -m pipenv install
            pm2 restart $PROCESS_ID
          
          

