name: Tag

on:
  push:
    tags:
      "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set tag var
        id: vars
        run: |
          echo ::set-output name=current_tag::$(git describe --tags --abbrev=0 | cut -d. -f1)
          echo "PREVIOUS_HASH = $(git show HEAD --format="%P")" >> $GITHUB_ENV
          echo ${{ env.PREVIOUS_HASH }}
          echo ::set-output name=previous_tag::$(git describe --tags --abbrev=0 ${{ env.PREVIOUS_HASH }} | cut -d. -f1)
      - name: Print vars
        run: |
          echo ${{ steps.vars.outputs.current_tag }}
          echo ${{ steps.vars.outputs.previous_tag }}
      
      - name: Test this all
        if: ${{ steps.vars.outputs.current_tag == steps.vars.outputs.previous_tag }}
        run: echo "YESS"
