name: Tag

on:
  push:
    tags:
      "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set tag var
        id: vars
        run: |
          git fetch -a
          echo ::set-output name=current_major::$(git tag --sort "-committerdate" | cut -d$'\n' -f1 | cut -d. -f1)
          echo ::set-output name=previous_major::$(git tag --sort "-committerdate" | cut -d$'\n' -f2 | cut -d. -f1)
      - name: Print vars
        run: |
          echo ${{ steps.vars.outputs.current_major }}
          echo ${{ steps.vars.outputs.previous_major }}
      
      - name: Test this all
        if: ${{ steps.vars.outputs.current_major == steps.vars.outputs.previous_major }}
        run: echo "YESS"
