name: Tag

on:
  push:
    tags:
      "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set tag var
        id: vars
        run: |
          git fetch -a
          echo ::set-output name=current_tag::$(git tag --sort "-committerdate" | cut -d$'\n' -f1)
          echo ::set-output name=previous_tag::$(git tag --sort "-committerdate" | cut -d$'\n' -f2)
      - name: Print vars
        run: |
          echo ${{ steps.vars.outputs.current_tag }}
          echo ${{ steps.vars.outputs.previous_tag }}
      
      - name: Test this all
        if: ${{ steps.vars.outputs.current_tag == steps.vars.outputs.previous_tag }}
        run: echo "YESS"
