name: Tag

on:
  push:
    tags:
      "v*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set tag var
        id: vars
        run: |
          echo ::set-output name=current_tag::$(git describe --tags --abbrev=0 | cut -d. -f1)
          echo ::set-output name=previous_hash::$(git log -1 --format='%H' --skip 1)
          echo ${{ steps.vars.outputs.previous_hash }}
          git log -1 --format='%H' --skip 2
          git log -1 --format='%H' --skip 1
          git log -1 --format='%H' 
          echo ::set-output name=previous_tag::$(git describe --tags --abbrev=0 $(git log -1 --format='%H' --skip 2) | cut -d. -f1)
      - name: Print vars
        run: |
          echo ${{ steps.vars.outputs.current_tag }}
          echo ${{ steps.vars.outputs.previous_tag }}
      
      - name: Test this all
        if: ${{ steps.vars.outputs.current_tag == steps.vars.outputs.previous_tag }}
        run: echo "YESS"
